# Generated by Django 5.1.7 on 2025-04-02 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locationName", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=100, unique=True)),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "itemLocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.location"
                    ),
                ),
            ],
        ),
    ]
